# Generated by Django 5.1.1 on 2024-09-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
