# Generated by Django 5.1.1 on 2024-09-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='house_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='House number'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Street'),
        ),
    ]
