# Generated by Django 5.1.1 on 2024-09-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_housing_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='is_deleted',
        ),
    ]
