# Generated by Django 5.1.1 on 2024-09-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_housing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
